# -*- coding: utf-8 -*-
"""Tp_Aprendizaje Automático Supervisado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6O9-Gkv-02ySdpDmcx77ZGSjcDvy26i
"""

def analizar_accion(accion:str, tiempo:int):
    if tiempo < 0 or tiempo > 300:
        return "Tiempo inválido"

    if accion == "combate":
        if tiempo >= 0 and tiempo >= 120:
            return ("victoria")
        else:
            return ("derrota")

    elif accion == "exploracion":
        if tiempo >= 250:
            return ("Descubrimiento")
        else:
            return ("sin hallazgos")

    elif accion == "interaccion social":
            return ("Mensaje enviado")


prueba = analizar_accion("exploracion", 301)

print(prueba)